# Generated by Django 4.1.4 on 2022-12-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
